version: "3"
services:
  tivix-test:
    container_name: tivix-test
    image: latest/tivix-test
    restart: always
    build: .
    ports:
      - "6001:6002"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'